// Frontend/client/src/components/CartSidebar.vue
<script setup>
import { useCartStore } from '../stores/cartStore'
import { useRouter } from 'vue-router'

const cartStore = useCartStore()
const router = useRouter()

const checkout = () => {
  cartStore.toggleSidebar(false)
  router.push('/checkout')
}
</script>

<template>
  <div :class="['cart-sidebar', { open: cartStore.isOpen }]">
    <div class="cart-header bg-primary text-white p-3 d-flex justify-content-between align-items-center">
      <h5 class="m-0"><i class="bi bi-cart3 me-2"></i>Your Cart</h5>
      <button class="btn-close btn-close-white" @click="cartStore.toggleSidebar(false)"></button>
    </div>

    <div class="cart-body p-3">
      <p v-if="cartStore.items.length === 0" class="text-center text-muted mt-5">Your cart is empty.</p>
      
      <div v-else class="cart-items-wrapper">
        <div v-for="item in cartStore.items" :key="item._id" class="cart-item card mb-2 border-0 shadow-sm">
          <div class="card-body d-flex justify-content-between align-items-center py-2 px-3">
            <div>
              <h6 class="m-0 fw-bold">{{ item.name }}</h6>
              <small class="text-muted">{{ item.price }} EGP x {{ item.qty }}</small>
            </div>
            <div class="d-flex align-items-center gap-3">
              <span class="fw-bold text-success">{{ item.price * item.qty }} EGP</span>
              <button class="btn btn-sm btn-outline-danger" @click="cartStore.removeFromCart(item._id)">
                X
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div v-if="cartStore.items.length > 0" class="cart-footer p-3 bg-light border-top">
      <div class="d-flex justify-content-between mb-3 text-dark">
        <span class="fw-bold fs-5">Total:</span>
        <span class="fw-bold fs-5 text-primary">{{ cartStore.totalPrice }} EGP</span>
      </div>
      <button class="btn btn-warning w-100 fw-bold py-2 mb-2" @click="cartStore.clearCart()">Clear Cart</button>
      <button class="btn btn-success w-100 fw-bold py-2 shadow-sm" @click="checkout">Checkout Process</button>
    </div>
  </div>

  <div v-if="cartStore.isOpen" class="cart-overlay" @click="cartStore.toggleSidebar(false)"></div>
</template>

<style scoped>
.cart-sidebar {
  position: fixed;
  top: 0;
  right: -400px;
  width: 100%;
  max-width: 400px;
  height: 100vh;
  background-color: white;
  z-index: 1050;
  transition: right 0.3s ease-in-out;
  display: flex;
  flex-direction: column;
  box-shadow: -5px 0 15px rgba(0, 0, 0, 0.1);
}

.cart-sidebar.open {
  right: 0;
}

.cart-body {
  flex-grow: 1;
  overflow-y: auto;
}

.cart-overlay {
  position: fixed;
  top: 0;
  left: 0;
  width: 100vw;
  height: 100vh;
  background-color: rgba(0, 0, 0, 0.5);
  z-index: 1040;
}
</style>

// Frontend/client/src/Components/CartSidebar.jsx
import { useCart } from "../context/CartContext";
import axiosInstance, { getImageUrl } from "../config/axiosInstance";

function CartSidebar({ isOpen, onClose }) {
  const { cartItems, removeFromCart, clearCart } = useCart();
  const user = JSON.parse(localStorage.getItem("user"));

  const totalPrice = cartItems.reduce((acc, item) => acc + item.price * item.qty, 0);

  const handleCheckout = async () => {
    if (!user) {
      alert("Please login to checkout");
      return;
    }
    try {
      const response = await axiosInstance.post("/orders", {
        orderItems: cartItems,
        totalPrice,
      }, {
        headers: { Authorization: `Bearer ${user.token}` }
      });
      alert("Checkout successful! Order mock created.");
      clearCart();
      onClose();
    } catch (error) {
      alert(error.response?.data?.message || "Checkout failed");
    }
  };

  if (!isOpen) return null;

  return (
    <div className="cart-sidebar shadow position-fixed top-0 end-0 h-100 bg-white" style={{ width: "350px", zIndex: 1050, overflowY: "auto" }}>
      <div className="p-3 border-bottom d-flex justify-content-between align-items-center">
        <h4 className="m-0">Shopping Cart</h4>
        <button className="btn btn-close" onClick={onClose}></button>
      </div>
      <div className="p-3">
        {cartItems.length === 0 ? (
          <p>Your cart is empty.</p>
        ) : (
          <div className="d-flex flex-column gap-3">
            {cartItems.map((item) => (
              <div key={item.product} className="d-flex gap-2 border p-2 rounded align-items-center">
                <img 
                  src={getImageUrl(item.image)} 
                  alt={item.name} 
                  style={{ width: "50px", height: "50px", objectFit: "cover" }} 
                  onError={(e) => { e.target.onerror = null; e.target.src = "https://via.placeholder.com/50"; }}
                />
                <div className="flex-grow-1">
                  <h6 className="m-0">{item.name}</h6>
                  <small className="text-muted">{item.qty} x {item.price} EGP</small>
                </div>
                <button className="btn btn-sm btn-danger" onClick={() => removeFromCart(item.product)}>X</button>
              </div>
            ))}
          </div>
        )}
      </div>
      {cartItems.length > 0 && (
        <div className="p-3 border-top mt-auto">
          <div className="d-flex justify-content-between fw-bold mb-3">
            <span>Total:</span>
            <span>{totalPrice} EGP</span>
          </div>
          <button className="btn btn-success w-100" onClick={handleCheckout}>Checkout</button>
        </div>
      )}
    </div>
  );
}

export default CartSidebar;
